### PR TITLE
Fix issue with global.HermesIternal

### LINKED ISSUE #71: Cannot find name 'global'.ts(2304)
Im getting `Cannot find name 'global'.ts(2304)` typescript error in App.tsx at global.HermesInternal. Im using VS code.

### PR DESCRIPTION
**Pull request by radko93**
# Summary
Fixes #71
Actually `HermesIternal` was added to `types/react-native` a long time ago but we just have to use it in the right way.

### CODE REVIEW

File: template/App.tsx [hunk 1]
```diff
@@ -35,7 +36,7 @@ const App = () => {
           contentInsetAdjustmentBehavior="automatic"
           style={styles.scrollView}>
           <Header />
-          {global.HermesInternal == null ? null : (
+          {!usingHermes ? null : (
```
Comment (emin93) [inline template/App.tsx]: Isn't it enough to just remove the global prefix? I would prefer to not change too much about the logic here.

Comment (radko93) [reply template/App.tsx]: No, because Jest fails without it. It was actually there but it was removed https://github.com/react-native-community/react-native-template-typescript/pull/55

Comment (MateusAndrade) [reply template/App.tsx]: Just tested here on a new project on Android/IOS and it works fine, without throwing any errors at ```global```
