### PR TITLE
Fix ESLint setup

### LINKED ISSUE #237: Typescript 4.4.4 not supported by @typescript-eslint/typescript-estree
## Expected results
Linting working out of the box when installing React Native with the Typescript template

## Observed results

Linting throws an error. Seems to be caused by an unsupported version of Typescript [introduced recently](https://github.com/react-native-community/react-native-template-typescript/commit/e5fce57edb5bba057105eff9bfc26dafe4aa460a).

### Logs
```
$ eslint . --ext .js,.jsx,.ts,.tsx
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.1.0

YOUR TYPESCRIPT VERSION: 4.4.4

Please only submit bug reports when using the officially supported version.
```

## Steps to reproduce

1. `$ npx react-native init --template typescript Project`
2. `$ yarn lint`

### PR DESCRIPTION
**Pull request by friederbluemle**
There are several issues related to the current ESLint/TypeScript setup with the latest version of this template.

Steps to reproduce:

1. Create new project: `npx react-native init rntsapp --template react-native-template-typescript`
2. Run `yarn lint`
3. Observe errors

```
error  Definition for rule '@typescript-eslint/no-shadow' was not found  @typescript-eslint/no-shadow
```

and

```
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
```

Also, `.eslintrc.js` contained a few quote warnings/errors that were also fixed.

```
/path/rntsapp/.eslintrc.js
  1:1   error    Definition for rule '@typescript-eslint/no-shadow' was not found                                    @typescript-eslint/no-shadow
  5:5   error    Replace `"no-shadow":·"off"` with `'no-shadow':·'off'`                                              prettier/prettier
  5:5   warning  Strings must use singlequote                                                                        quotes
  5:18  warning  Strings must use singlequote                                                                        quotes
  6:5   error    Replace `"@typescript-eslint/no-shadow":·["error"` with `'@typescript-eslint/no-shadow':·['error'`  prettier/prettier
  6:5   warning  Strings must use singlequote                                                                        quotes
  6:38  warning  Strings must use singlequote                                                                        quotes
```

Related: #112 #150 #238

Fixes #237

### CODE REVIEW

File: template/_prettierrc.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 module.exports = {
+  arrowParens: 'avoid',
+  bracketSameLine: true,
   bracketSpacing: false,
-  jsxBracketSameLine: true,
```
Comment (emin93) [inline template/_prettierrc.js:3]: I know that this has been deprecated, but since this template aims to be consistent with the default RN template, I advise you to create a PR for that in the RN repo: https://github.com/facebook/react-native/blob/v0.66.4/template/_prettierrc.js

File: template/_prettierrc.js [hunk 2]
```diff
@@ -1,7 +1,7 @@
 module.exports = {
+  arrowParens: 'avoid',
```
Comment (emin93) [inline template/_prettierrc.js:2]: Here also, please undo the re-sort, so it's consistent with the default RN template.

**Review by emin93 — CHANGES_REQUESTED** [review]
Hi @friederbluemle,

Thanks for the PR. The changes related to fixing ESLint look good and are welcome.

The unrelated changes I advise you to create a PR in the RN repo, so we can move it over as soon it's merged there.

File: template/_eslintrc.js [hunk 3]
```diff
@@ -1,8 +1,10 @@
 module.exports = {
   root: true,
   extends: '@react-native-community',
+  parser: '@typescript-eslint/parser',
+  plugins: ['@typescript-eslint'],
   rules: {
-    "no-shadow": "off",
-    "@typescript-eslint/no-shadow": ["error"],
+    'no-shadow': 'off',
```
Comment (emin93) [inline template/_eslintrc.js:7]: I'm happy with leaving this change in. Consistent quotes 💯 😄

File: template/_prettierrc.js (hunk 1 above)
Comment (friederbluemle) [reply template/_prettierrc.js:3]: Makes sense! I only checked that `main` branch in `react-native`, which has this addressed already.

File: template/_prettierrc.js (hunk 2 above)
Comment (friederbluemle) [reply template/_prettierrc.js:2]: Okay, I'll undo this, and we'll wait until this arrives in the next release of `react-native`.

**Comment by friederbluemle** [comment]
Hi @emin93 - Thanks for the super fast review. I agree with what you said and removed the commit that changes .prettierrc.js

**Review by emin93 — APPROVED** [review]
Looks good, thanks for the updates 👍

**Comment by mikehardy** [comment]
Sorry about the no shadow issue! That was cherry picked from a config change I needed but didn't work in isolation I guess. Is there no CI here that runs these things?I could look into that if not

**Review by mikehardy — APPROVED** [review]
Didn't realize those deps for no shadow weren't here yet, bad testing on my part from last PR

**Comment by emin93** [comment]
@mikehardy Good idea with testing this in the CI. You are more than welcome to look into it. 👍
